---
title: "Simulation"
author: "ICM Team 55329"
date: "1/20/2017"
output: html_document
---

To run this program, you need to install some packages if you have not.
```{r installPackages}
install.packages(ggplot2)
install.packages(magrittr)
install.packages(tidyr)
install.packages(dplyr)
install.packages(mixtools)
install.packages(msm)
```


```{r setup}
library(ggplot2)
library(magrittr)
library(tidyr)
library(dplyr)
library(mixtools)
library(msm)
library(parallel)
```

```{r setIndex}
testHours <- 0.2
nPas <- 720
nDoc <- 10
nSec <- 10
meanDoc <- 10
meanBag <- 10
lambda <- c(0.6,0.3,0.1)
meanBody <- c(10,10,10)
sigma <- c(1,1,1)
limitLineSec <- 4
```

```{r initialize}
#Status of Document Check Counter
#n  -> Occupied, n stands for current passanger
#-1 -> Available
#-2 -> Closed     --------------------------> develop in the future
testTime <- ceiling(testHours * 60 * 60) #measure in time
statusPas <- rep(0,nPas)
timeLeftPas <- rep(0,nPas)
doc <- rep(-1,nDoc)
lineDoc <- data.frame()
#generate random arrival time by exponential distribution
#timeArrivalPas <- rexp(n=nPas, rate=nPas/testTime)
timeArrivalPas <- rep(2,nPas)
timeArrivalPas[1] <- round(timeArrivalPas[1])
for (i in 2:nPas) {
  timeArrivalPas[i] <- round(timeArrivalPas[i] + timeArrivalPas[i-1])
}
timeEndPas <- rep(0,nPas)
timeTest <- rep(0,nPas)
timeDoc <- round(rtnorm(nPas, mean = meanDoc, sd = 1, lower=1, upper=testTime))
#timeDoc <- rep(2,nPas)
#timeBag <- rep(2,nPas)
timeBag <- round(rtnorm(nPas, mean = meanBag, sd = 1, lower=1, upper=testTime))
#timeDoc[timeDoc <= 0] <- meanDoc
#timeBag[timeBag <= 0] <- meanBag

timeBody<-round(rmvnormmix(nPas,lambda, meanBody, sigma))
timeBody[timeBody <= 0] <- meanBody[1]
#timeBody <- rep(2,nPas)

pas <- data.frame(timeArrivalPas, timeDoc, timeBody, timeBag, statusPas, timeLeftPas, timeTest, timeEndPas)
sec <- rep(-1,nSec)
lineSec <- data.frame()
lengthLineDoc <- data.frame()
lengthLineSec <- data.frame()
```

```{r testUse}
plot(timeDoc)
plot(sort(timeDoc))
```

```{r process}
#0-have not come
#1-wait before document check
#2-document check
#3-wait before body scan
#4-body scan
#5-end
controlDoc <- function(lengthLine){
  if (lengthLine < limitLineSec) {
    return(TRUE)#should not control and stop zone A's running
  }
  else{
    return(FALSE)#shoud stop the running of zone A
  }
}

time <- 0
#add people to the line when time is 0
for (j in 1:nPas){
#while (as.numeric(pas[j,"timeArrivalPas"]) <= as.numeric(time)) {   
  if(pas[j,"timeArrivalPas"] == time) {
    lineDoc[nrow(lineDoc)+1,1] <- j #move this passenger to the line
    pas[j,"statusPas"] <- 1 #change the status for the passenger
  }
}

while (time < testTime*1.5){
  print(time)
#for (time in 0:testTime){#modify status every second, define time as well
  
  ###PROCESS OF SECURITY CHECK###
  
  #2-ITERATE ALL SECURITY CHECK LINES
  for (j in 1:length(sec)){ #iterate all security points
    cat("timeLeft:",pas[sec[j],"timeLeftPas"])
    if(sec[j] == -1){   #2.1-if the counter is available
      if(nrow(lineSec) > 0){#2.1.1-if there are somebody in the line
        sec[j] <- lineSec[1,1]  #update status for the security point
        if(nrow(lineSec) <= 1){
          lineSec <- data.frame()
        }
        else{
          lineSec <- data.frame(lineSec[-1,]) #remove the passanger from the line
        }
        pas[sec[j],"statusPas"] <- 4
        pas[sec[j],"timeLeftPas"] <- pas[sec[j],"timeBody"] #countdown the item time
        if(pas[sec[j],"timeTest"] == time - 1){
            pas[sec[j],"timeLeftPas"] <- pas[sec[j],"timeLeftPas"] - 1
        }
      }
    } else if(sec[j] > -1){#2.2-if the counter is occupied
      if(pas[sec[j],"timeLeftPas"] <= 1){#2.2.1-if the man is ready to go
        #put the passenger into next line
        #lineSec[nrow(lineSec)+1,1] <- doc[j] add this passenger to next line
        #update the passenger status and add picking up bags time
        pas[sec[j],"statusPas"] <- 5
        
        #print(pas[sec[j],"timeBag"])
        #print(pas[sec[j],"timeBody"])
        if(pas[sec[j],"timeBag"] > pas[sec[j],"timeBody"]){#if the passenger need to wait for bags
          pas[sec[j],"timeEndPas"] <- (time + pas[sec[j],"timeBag"] - pas[sec[j],"timeBody"])
        }
        else{#if the passenger do not need to wait for bags
          pas[sec[j],"timeEndPas"] <- time    #stop here
        }
        sec[j] <- -1 #remove the passanger from the counter
        if(nrow(lineSec) > 0){
          sec[j] <- lineSec[1,1] #get next passenger
          if(nrow(lineSec) <= 1){
            lineSec <- data.frame()
          }
          else{
            lineSec <- data.frame(lineSec[-1,]) #remove the passanger from the line
          }
          pas[sec[j],"statusPas"] <- 4 #update passenger status 
          pas[sec[j],"timeLeftPas"] <- pas[sec[j],"timeBody"] #countdown starts
        }
      }
      else{ #2.2.2-if the man is not ready to go
        cat("\n2.2.2")
        pas[sec[j],"timeLeftPas"] <- pas[sec[j],"timeLeftPas"] - 1#change countdown
      }
    }
  }
  
  ###ADD NEW PEOPLE TO THE LINE###
  if(time > 0){
  for (j in 1:nPas){
  #while (as.numeric(pas[j,"timeArrivalPas"]) <= as.numeric(time)) {   
    if(pas[j,"timeArrivalPas"] == time) {
      lineDoc[nrow(lineDoc)+1,1] <- j #move this passenger to the line
      pas[j,"statusPas"] <- 1 #change the status for the passenger
    }
  }
  }
  
  ###PROCESS OF DOCUMENT CHECK AND FIRST LINE###
  #ITERATE ALL COUNTERS
  for (j in 1:length(doc)){ #iterate all counters
    #Dynamic Control Flow of Zone A
    if(doc[j] == -1){   #2.1-if the counter is available
      if(nrow(lineDoc) > 0){#2.1.1-if there are somebody in the line
        doc[j] <- lineDoc[1,1]  #update status for the counter
        if(nrow(lineDoc) == 1){
          lineDoc <- data.frame()
        }
        else{
          lineDoc <- data.frame(lineDoc[-1,]) #remove the passanger from the line
        }
        pas[doc[j],"statusPas"] <- 2
        pas[doc[j],"timeLeftPas"] <- pas[doc[j],"timeDoc"] #countdown the item time
      }
    } else if(doc[j] > -1){#2.2-if the counter is occupied
      if(pas[doc[j],"timeLeftPas"] == 1 && controlDoc(nrow(lineSec))){#2.2.1-if the man is ready to go and lineSec is open
        #put the passenger into next line
        pas[doc[j],"timeTest"] <- time
        lineSec[nrow(lineSec)+1,1] <- doc[j]
        pas[doc[j],"statusPas"] <- 3 #update passenger status
        doc[j] <- -1 #remove the passanger from the counter
        if(nrow(lineDoc) > 0){
          doc[j] <- lineDoc[1,1] #get next passenger
          if(nrow(lineDoc) == 1){
          lineDoc <- data.frame()
          }
          else{
            lineDoc <- data.frame(lineDoc[-1,]) #remove the passanger from the line
          }
          pas[doc[j],"statusPas"] <- 2 #update passenger status 
          pas[doc[j],"timeLeftPas"] <- pas[doc[j],"timeDoc"] #countdown starts
        }
      } else if(pas[doc[j],"timeLeftPas"] > 1){#2.2.2-if the man is not ready to go
        pas[doc[j],"timeLeftPas"] <- pas[doc[j],"timeLeftPas"] - 1#change countdown
      }
    }
  }
  lengthLineDoc[nrow(lengthLineDoc)+1,1] <- nrow(lineDoc)
  lengthLineSec[nrow(lengthLineSec)+1,1] <- nrow(lineSec)
  #print(lineSec)
  #cat("sec[j]b:",sec[j])
  time <- time + 1
}
```

```{r result}
pas <- pas %>%
  mutate(waitTime = timeEndPas - timeArrivalPas)
var <- var(pas$waitTime)
plot(pas$waitTime)
plot(lengthLineDoc[,1])
plot(lengthLineSec[,1])
```


```{r parallel}
mclapply(1:5,function(i){print(i)})
```


```{r new:Combine}
result
```

```{r visiulization}
result_one <- read.csv("/Users/apple/GoogleDrive/MCM2017/r/results/final_result.csv", stringsAsFactors=FALSE)
result_one %>%
  ggplot(aes(x=numOfA, y=throughput)) + geom_point()
result_one %>%
  ggplot(aes(x=numOfA, y=varience)) + geom_point()
```

```{r visiulization_pcr}
pcr <- data.frame(ratioOfPreCheck = c(2,43/17,3,47/13,5,11,2,43/17,3,47/13,5,11), tmean = c(293.9826, 252.4186, 173.5285, 190.092, 157.5449, 165.0696, 61.20739, 60.40353, 60.78449, 62.60554, 110.4227, 409.1716), type = c(rep("normal",6),rep("pre",6)))
pcr %>%
  ggplot(aes(x=ratioOfPreCheck, y=tmean, color=type)) + geom_line()
pcr <- data.frame(ratioOfPreCheck = c(2,43/17,3,47/13,5,11,2,43/17,3,47/13,5,11), varience = c(4512.152, 1511.715, 537.6769, 1472.271, 415.4593, 636.2153, 399.2409, 411.3647, 430.3976, 422.1906, 2202.418, 44306.22), type = c(rep("normal",6),rep("pre",6)))
pcr %>%
  ggplot(aes(x=ratioOfPreCheck, y=varience, color=type)) + geom_line()
```

```{r visualizationBp}
tmeaniee <- data.frame(IndexOfEqualityEgo = c(0,25,50,75,100), tmeans =  c(751,609,519,463,448), tag = rep("tmean",5))

varIee <- data.frame(IndexOfEqualityEgo = c(0,25,50,75,100), variance=c(121686,60111,31858,19789,17702),rep("ver",5))
tpIee <- data.frame(IndexOfEqualityEgo = c(0,25,50,75,100), throughput=c(0.16,0.32,0.45,0.51,0.53),rep("throughput",5))
tmeaniee %>%
  ggplot(aes(x=IndexOfEqualityEgo, y=tmeans)) + geom_line()
varIee %>%
  ggplot(aes(x=IndexOfEqualityEgo, y=variance)) + geom_line()
tpIee %>%
  ggplot(aes(x=IndexOfEqualityEgo, y=throughput)) + geom_line()
```

```{r visualizationpd}
tmeaniee <- data.frame(PD = c(1.5,1.7,2,2.4,3,4), tmeans =  c(446,461,454,448,463,519), tag = rep("tmean",6))

varIee <- data.frame(PD = c(1.5,1.7,2,2.4,3,4), variance=c(24164,26023,16751,17702,19790,31858),rep("ver",6))
tpIee <- data.frame(PD = c(1.5,1.7,2,2.4,3,4), throughput=c(0.54,0.51,0.54,0.53,0.49,0.44),rep("throughput",6))
tmeaniee %>%
  ggplot(aes(x=PD, y=tmeans)) + geom_line()
varIee %>%
  ggplot(aes(x=PD, y=variance)) + geom_line()
tpIee %>%
  ggplot(aes(x=PD, y=throughput)) + geom_line()
```